### ISSUE TITLE
Fish support?

### ISSUE THREAD

**Issue by legendofmiracles** [irevenko/tsukae#3]
Haven't tried it, but the readme only states zsh and bash

**Comment by irevenko** [comment]
As far as i know fish shell has the same file structure as bash. I only need to figure out where ```.fish_history``` is located

**Comment by legendofmiracles** [comment]
it's in `~/.local/share/fish/fish_history`.

It's a yaml file, and it's structured like this:
```
- cmd: mkdir .local/share/nvm
  when: 1610797953
- cmd: ./polybar.sh
  when: 1610798193
- cmd: set -U fish_user_paths ~/bin $fish_user_paths
  when: 1610798240
- cmd: sudo pacman -S pipewire pipewire-alsa pipewire-pulse pipewire-jack
  when: 1610798273
- cmd: git diff README.md
  when: 1610798415
  paths:
    - README.md
  ```
